### ISSUE TITLE
use of internal package not allowed

### ISSUE THREAD

**Issue by nEdAy** [shiguanghuxian/face-login#2]
您好，这是我的配置：
Windows 10
Go 1.10.2
GoLand

执行make build时，
main.go:19:2: use of internal package not allowed

目标代码是 import "github.com/shiguanghuxian/face-login/internal/common"
卡在这一个多小时了 有什么建议么

**Comment by shiguanghuxian** [comment]
正确的做法应该是
1. `go get github.com/shiguanghuxian/face-login`
2. `cd $GOPATH/src/github.com/shiguanghuxian/face-login`
3. `go build`

之所已超不到 import "github.com/shiguanghuxian/face-login/internal/common" 是因为包在internal文件夹，这个文件夹只能本程序使用是私有的，外部程序不能引用

**Comment by nEdAy** [comment]
理解了这个internal了

**Comment by shiguanghuxian** [comment]
还有什么问题嘛

**Comment by nEdAy** [comment]
感谢，我之前没接触过Go,打算从这个项目入手学习下，
现在编译器没问题可以运行了，但调试时候Log：

2018/05/28 15:05:14 写pid文件错误
2018/05/28 15:05:14 config.go:50: C:\Users\15827\AppData\Local\Temp\config\config.toml
ERROR: Logging before logger.Init.
FATAL: 2018/05/28 15:05:14.087937 faceserver.go:32: 配置文件读取失败: open C:\Users\15827\AppData\Local\Temp\config\config.toml: The system cannot find the file specified.

config.toml读取失败 直接就退出了...

**Comment by nEdAy** [comment]
找到了 是这个吧 face-login\build\config

**Comment by shiguanghuxian** [comment]
打开cmd进入项目目录，执行 `make build` 然后进入项目下的build目录，执行faceserver.exe

**Comment by nEdAy** [comment]
可以了 ， 我可以联调小程序了
如果我改用face++的话  配置文件里面的 faceset_token 从哪里获取啊 我在官网后台没找到

**Comment by nEdAy** [comment]
Seeta 写的 cmd = "/Users/zuo/Documents/c++/SeetaFaceEngine/face/build/"
我一会儿也去找个试试

**Comment by shiguanghuxian** [comment]
faceset_token 你可以调用相关接口生成一个， 你可以设置成从配置文件读取，我的好像写死了。
参考：https://github.com/shiguanghuxian/face-golang-sdk

Seeta如果要用这个的话需要你编译一个项目
项目地址：https://github.com/shiguanghuxian/face-cmd

**Comment by nEdAy** [comment]
昨天下班就走了 face++ 调试ok
Seeta 编译需要openCV 好慢 应该也没太大问题
再次感谢作者 节省了我很多时间

**Comment by iamzken** [comment]
> 正确的做法应该是
> 
> 1. `go get github.com/shiguanghuxian/face-login`
> 2. `cd $GOPATH/src/github.com/shiguanghuxian/face-login`
> 3. `go build`
> 
> 之所已超不到 import "github.com/shiguanghuxian/face-login/internal/common" 是因为包在internal文件夹，这个文件夹只能本程序使用是私有的，外部程序不能引用

您好，按照您的做法试了试，我这里还是报错：
		"github.com/shiguanghuxian/face-login/internal/common"

![image](https://user-images.githubusercontent.com/10125384/47130881-5242b700-d2ce-11e8-9a0b-c8ab62ea5b2b.png)
请您帮我分析一下

**Comment by shiguanghuxian** [comment]
@iamzken 我看你编译目录在E:\ai-study，你应该在github.com/shiguanghuxian/face-login目录编译，不然internal还是不在你当前编译目录下，不允许被引用

**Comment by iamzken** [comment]
> @iamzken 我看你编译目录在E:\ai-study，你应该在github.com/shiguanghuxian/face-login目录编译，不然internal还是不在你当前编译目录下，不允许被引用



> @iamzken 我看你编译目录在E:\ai-study，你应该在github.com/shiguanghuxian/face-login目录编译，不然internal还是不在你当前编译目录下，不允许被引用

![image](https://user-images.githubusercontent.com/10125384/47200610-6f988380-d3a9-11e8-8eae-9ffe651707af.png)


我去E:/ai-study/github.com/shiguanghuxian/face-login目录下编译，还是报一样的错误.............

**Comment by iamzken** [comment]
我的go版本是1.11

**Comment by shiguanghuxian** [comment]
@iamzken 
请检查两点
1.E:/ai-study是GOPATH
2.系统是否有多个GOPATH

另外你可以在项目根目录执行 make build 命令编译

**Comment by iamzken** [comment]
嗯，多谢您耐心的解答，我找到问题了，GOPATH不对，谢谢

**Comment by iamzken** [comment]
@shiguanghuxian 我跑了一下您的项目，都是相关的http接口和相关测试样例代码，没有相关的页面实现。之后有写页面的打算吗？

**Comment by shiguanghuxian** [comment]
@iamzken 
做这个的初衷是为了实现一套基于微信小程序的人脸登录流程，因为小程序在微信内，用人脸安全上没问题，可以参考[https://github.com/shiguanghuxian/face-login-wx](https://github.com/shiguanghuxian/face-login-wx)的README.md文件

最近比较忙，后期会做一些界面和功能优化

**Comment by shiguanghuxian** [comment]
@iamzken 有什么好的想法和建议可以联系我
